[General]
loglevel = notify
bypass-system = true
dns-server = 1.1.1.1, 8.8.8.8
update-url = https://raw.githubusercontent.com/yseavlong2010-dotcom/NOXERA/refs/heads/main/Shadow_VIP.conf
[Rule]
=== LUONG DANG NHAP DIRECT (CHONG LOI MANG) ===
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,facebook.com,DIRECT
DOMAIN-SUFFIX,facebook.net,DIRECT
DOMAIN-SUFFIX,google.com,DIRECT
DOMAIN-SUFFIX,googleapis.com,DIRECT
DOMAIN-SUFFIX,gstatic.com,DIRECT
DOMAIN-KEYWORD,garena-sso,DIRECT
DOMAIN-KEYWORD,auth,DIRECT
DOMAIN-KEYWORD,login,DIRECT
=== KHIEN BAO VE TAI KHOAN ===
DOMAIN-KEYWORD,crashreport,REJECT
DOMAIN-KEYWORD,telemetry,REJECT
DOMAIN-KEYWORD,anticheat,REJECT
=== LUONG GAME ===
DOMAIN-SUFFIX,garena.com,Proxy
DOMAIN-SUFFIX,freefiremobile.com,Proxy
FINAL,DIRECT
[Script]
CHÚ Ý: Toàn bộ lệnh dưới đây PHẢI nằm trên 1 dòng duy nhất, TUYỆT ĐỐI không được nhấn Enter xuống dòng.
azexl_ff_main = type=http-response,pattern=^https://..freefiremobile.com/.,requires-body=1,max-size=524288,script-path=https://raw.githubusercontent.com/yseavlong2010-dotcom/NOXERA/refs/heads/main/AimX.js
azexl_garena_main = type=http-response,pattern=^https://..garena.com/.,requires-body=1,max-size=524288,script-path=https://raw.githubusercontent.com/yseavlong2010-dotcom/NOXERA/refs/heads/main/AimX.js
[MITM]
enable = true
hostname = *.freefiremobile.com, *.garena.com
