[General]
loglevel = notify
bypass-system = true
dns-server = 1.1.1.1, 8.8.8.8
[Rule]
=== DANH SÁCH BỎ QUA ĐĂNG NHẬP (DIRECT) ===
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,facebook.com,DIRECT
DOMAIN-SUFFIX,facebook.net,DIRECT
DOMAIN-SUFFIX,google.com,DIRECT
DOMAIN-SUFFIX,googleapis.com,DIRECT
=== LUỒNG ĐỊNH TUYẾN MẠNG ===
FINAL,DIRECT
[Script]
LƯU Ý: Mỗi dòng lệnh Script dưới đây PHẢI nằm trên một dòng duy nhất, tuyệt đối không xuống dòng.
locket_pro_mock = type=http-response,pattern=^https?://api.revenuecat.com/v1/(subscribers|receipts)/.,requires-body=1,max-size=524288,script-path=https://raw.githubusercontent.com/yseavlong2010-dotcom/NOXERA/refs/heads/main/subscription_mock.js
general_app_mock = type=http-response,pattern=^https?://..revenuecat.com/v1/(subscribers|receipts)/.*,requires-body=1,max-size=524288,script-path=https://raw.githubusercontent.com/yseavlong2010-dotcom/NOXERA/refs/heads/main/subscription_mock.js
[MITM]
enable = true
Chỉ giải mã các máy chủ phân phối dịch vụ gói mua trong ứng dụng
hostname = api.revenuecat.com, *.revenuecat.com
