[General]
loglevel = notify
bypass-system = true
dns-server = 1.1.1.1, 8.8.8.8
[Rule]
=== 1. LUỒNG ĐĂNG NHẬP (BẮT BUỘC ĐI THẲNG - CHỐNG LỖI MẠNG) ===
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,facebook.com,DIRECT
DOMAIN-SUFFIX,facebook.net,DIRECT
DOMAIN-SUFFIX,google.com,DIRECT
DOMAIN-SUFFIX,googleapis.com,DIRECT
DOMAIN-KEYWORD,sso.garena,DIRECT
DOMAIN-KEYWORD,auth.garena,DIRECT
DOMAIN-KEYWORD,account.garena,DIRECT
DOMAIN-KEYWORD,login,DIRECT
=== 2. KHIÊN ANTI-BAN (CHẶN MÁY CHỦ QUÉT GIAN LẬN) ===
DOMAIN-KEYWORD,crashreport,REJECT
DOMAIN-KEYWORD,telemetry,REJECT
DOMAIN-KEYWORD,apm.garena,REJECT
DOMAIN-KEYWORD,anticheat,REJECT
=== 3. LUỒNG GAME (ĐI QUA VPS VMESS CỦA BẠN ĐỂ CÓ TÁC DỤNG) ===
DOMAIN-SUFFIX,garena.com,Proxy
DOMAIN-SUFFIX,freefiremobile.com,Proxy
FINAL,DIRECT
[Script]
=== MODULE TIÊM SCRIPT ===
azexl_aim_drag = type=http-response,pattern=^https?://(client|config|patch|status|version|api).(freefiremobile|garena).com/.*,requires-body=1,max-size=524288,script-path=https://raw.githubusercontent.com/yseavlong2010-dotcom/NOXERA/refs/heads/main/AimX.js
[MITM]
enable = true
=== GIẢI MÃ CHỌN LỌC (Dùng dấu - để chừa các cổng đăng nhập ra) ===
hostname = client.freefiremobile.com, config.freefiremobile.com, patch.freefiremobile.com, status.freefiremobile.com, version.freefiremobile.com, api.freefiremobile.com, *.garena.com, -auth.garena.com, -sso.garena.com, -login.garena.com
